{
  "project_name": "{{PROJECT_NAME}}",
  "project_type": "{{PROJECT_TYPE}}",
  "stack": "{{STACK}}",
  "architecture_style": "{{ARCHITECTURE_STYLE}}",
  "vault_path": "{{VAULT_PATH}}",
  "vault_project_path": "{{VAULT_PROJECT_PATH}}",
  "vision_source": "{{VISION_PATH}}",
  "vision_mode": "{{VISION_MODE}}",
  "engineering_spec": "{{SPEC_PATH}}",
  "current_sprint": 1,
  "completed_sprints": [],
  "active_agents": [],
  "specialized_agents": [],
  "specialized_workflows": [],
  "specialized_skills": [],
  "clarifications_pending": {{CLARIFICATIONS_JSON_ARRAY}},
  "last_updated": "{{TODAY_ISO}}",
  "last_workflow_run": null,
  "last_workflow_stage": null,
  "last_workflow_result": null,
  "active_workflow_run": null,
  "workflow_runs": [],
  "last_task_completed": null,
  "repos": []
}
